# Generates a runnable FastAPI project using manifests and Jinja templates.
import os, shutil, yaml
from jinja2 import Template

BASE = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
WORKSPACE = os.path.join(BASE, "workspace")

TEMPLATES_DIR = os.path.join(BASE, "app", "templates")
MANIFESTS_DIR = os.path.join(BASE, "app", "services", "manifests")

def read(path):
    with open(path, "r", encoding="utf-8") as f:
        return f.read()

def write(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)

def render_template(template_name: str, **kwargs) -> str:
    tpl_path = os.path.join(TEMPLATES_DIR, template_name)
    tpl = Template(read(tpl_path))
    return tpl.render(**kwargs)

def load_manifest(name: str):
    p = os.path.join(MANIFESTS_DIR, f"{name}.yaml")
    with open(p, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)

def generate_project(plan: dict, project_name: str):
    project_root = os.path.join(WORKSPACE, project_name)
    if os.path.exists(project_root):
        shutil.rmtree(project_root)
    os.makedirs(project_root, exist_ok=True)

    # Basic scaffold
    write(os.path.join(project_root, "app", "main.py"),
          render_template("main_app.py.jinja", project_name=project_name))
    write(os.path.join(project_root, "requirements.txt"),
          "fastapi\nuvicorn\npython-dotenv\nstripe\nfirebase-admin\npydantic\n")

    # Apply integrations
    env_entries = set()
    for integ in plan.get("integrations", []):
        manifest = load_manifest(integ["name"])
        for k in manifest.get("env", []):
            env_entries.add(k)
        for tpl in manifest.get("templates", []):
            target_rel = tpl["target"]
            tpl_name = tpl["template"]
            write(os.path.join(project_root, target_rel),
                  render_template(tpl_name, project_name=project_name))

    # Dockerfile / Terraform optional
    if plan.get("deployment", {}).get("platform") == "gcp_cloud_run":
        write(os.path.join(project_root, "Dockerfile"),
              render_template("Dockerfile.jinja", project_name=project_name))
        write(os.path.join(project_root, "infra", "main.tf"),
              render_template("terraform_main.tf.jinja", project_name=project_name))
        write(os.path.join(project_root, "infra", "variables.tf"),
              render_template("terraform_variables.tf.jinja", project_name=project_name))
        write(os.path.join(project_root, "infra", "outputs.tf"),
              render_template("terraform_outputs.tf.jinja", project_name=project_name))

    # .env.example
    env_lines = [f"{k}=" for k in sorted(env_entries)]
    write(os.path.join(project_root, ".env.example"), "\n".join(env_lines) + "\n")

    # README
    readme = f"""# {project_name}

Generated by PlugGPT.

## Quickstart
```bash
python -m venv .venv && source .venv/bin/activate
pip install -r requirements.txt
cp .env.example .env   # fill Stripe/Firebase values
uvicorn app.main:app --reload --port 8001
```
"""
    write(os.path.join(project_root, "README.md"), readme)

    return {"project_root": project_root}
